# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoonitCameraDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoonitCameraDemo
  pod 'YoonitCamera', :git => "https://github.com/Yoonit-Labs/ios-yoonit-camera.git", :tag => '1.0.0'
  
  pod 'DropDown'
end
